
// -- user code here --

/* --- start generated code --- */

// Generated by Phaser Editor v1.4.1 (Phaser v2.6.2)


/**
 * Level.
 */
class Level extends Phaser.State {
	
	constructor() {
		
		super();
		
	}
	
	init() {
		
		this.scale.scaleMode = Phaser.ScaleManager.SHOW_ALL;
		this.scale.pageAlignHorizontally = true;
		this.scale.pageAlignVertically = true;
		this.stage.backgroundColor = '#ffffff';
		
		this.afterInit() ;
		
	}
	
	preload () {
		
		this.load.pack('game', 'assets/pack.json');
		
		this.afterPreload() ;
		
	};
	
	create() {
		var _Bt01 = this.add.button(110, 91, 'BA_StartBt', this.OnBt01, this, 0, 0, 1, 0);
		
		var _Bt02 = this.add.button(110, 213, 'BA_StartBt', this.OnBt02, this, 0, 0, 1, 0);
		
		var _Bt03 = this.add.button(110, 333, 'BA_StartBt', this.OnBt03, this, 0, 0, 1, 0);
		
		var _Bt04 = this.add.button(110, 460, 'BA_StartBt', this.OnBt04, this, 0, 0, 1, 0);
		
		var _Bt05 = this.add.button(110, 601, 'BA_StartBt', this.OnBt05, this, 0, 0, 1, 0);
		
		// public fields
		
		this.fBt01 = _Bt01;
		this.fBt02 = _Bt02;
		this.fBt03 = _Bt03;
		this.fBt04 = _Bt04;
		this.fBt05 = _Bt05;
		this.afterCreate() ;
		
	}
	
	public fBt01 : Phaser.Button;
	public fBt02 : Phaser.Button;
	public fBt03 : Phaser.Button;
	public fBt04 : Phaser.Button;
	public fBt05 : Phaser.Button;
	
	/* state-methods-begin */
	
	afterInit(){
	}
	
	afterPreload(){
	}
	
	afterCreate(){
	}
	
	OnBt01(){
	    console.log("Bt01") ;
	}
	
    OnBt02(){
        console.log("Bt02") ;
        this.fBt02.inputEnabled = !this.fBt02.inputEnabled ;
        if( this.fBt02.inputEnabled ){
            this.fBt02.setFrames(0,0,1,0) ;
        }
        else{
            this.fBt02.setFrames(2,2,2,2) ;
        }
        console.log("Enabled:"+this.fBt02.inputEnabled.toString()) ;
    }
    
    OnBt03(){
        console.log("Bt03") ;
        this.fBt02.inputEnabled = !this.fBt02.inputEnabled ;
        if( this.fBt02.inputEnabled ){
            this.fBt02.setFrames(0,0,1,0) ;
        }
        else{
            this.fBt02.setFrames(2,2,2,2) ;
        }
        console.log("Enabled:"+this.fBt02.inputEnabled.toString()) ;
    }
    
    OnBt04(){
        console.log("Bt04") ;
    }   
    
    OnBt05(){
        console.log("Bt05") ;
    }	

	/* state-methods-end */
	
}
/* --- end generated code --- */
// -- user code here --
